import { writeFileSync } from 'fs';
import { join } from 'path';
import { DataSource } from 'typeorm';
import { withDataSource } from './data-source';
import { Product } from './entities/product.entity';
import { captureLogger } from './lib/capture-logger';
import { typeormVersion } from './lib/versions';
import { DEFAULT_FILTER, getPaginationParams } from './queries/filter';

async function capture(fn: () => Promise<unknown>): Promise<string[]> {
  captureLogger.reset();
  captureLogger.enabled = true;
  try {
    await fn();
  } finally {
    captureLogger.enabled = false;
  }
  return captureLogger.captured.map((query) => query.sql);
}

const hasLimit = (sql: string[]): boolean => /\blimit\b/i.test(sql.join('\n'));

void withDataSource(async (ds: DataSource) => {
  const repository = ds.getRepository(Product);
  const { limit, skip } = getPaginationParams(DEFAULT_FILTER);
  const [{ v: dbVersion }] = await ds.query('SELECT VERSION() AS v');
  const ormVersion = typeormVersion();

  // 1. skip/take + a join + getRawMany
  const skipTakeSql = await capture(() =>
    repository
      .createQueryBuilder('product')
      .innerJoin('product.brand', 'brand')
      .select('product.id', 'id')
      .where('product.isActive = :isActive', { isActive: true })
      .orderBy('product.createdAt', 'DESC')
      .skip(skip)
      .take(limit)
      .getRawMany(),
  );

  // 2. offset/limit + a join + getRawMany
  const offsetLimitSql = await capture(() =>
    repository
      .createQueryBuilder('product')
      .innerJoin('product.brand', 'brand')
      .select('product.id', 'id')
      .where('product.isActive = :isActive', { isActive: true })
      .orderBy('product.createdAt', 'DESC')
      .offset(skip)
      .limit(limit)
      .getRawMany(),
  );

  // 3. getManyAndCount with joins on 1:N relations
  const getManyAndCountSql = await capture(() =>
    repository
      .createQueryBuilder('product')
      .leftJoinAndSelect('product.reviews', 'reviews')
      .leftJoinAndSelect('product.images', 'images')
      .where('product.isActive = :isActive', { isActive: true })
      .orderBy('product.createdAt', 'DESC')
      .skip(skip)
      .take(limit)
      .getManyAndCount(),
  );

  // 4. getCount() with and without a join
  const countWithJoinSql = await capture(() =>
    repository
      .createQueryBuilder('product')
      .innerJoin('product.brand', 'brand')
      .where('product.isActive = :isActive', { isActive: true })
      .getCount(),
  );

  const countWithoutJoinSql = await capture(() =>
    repository
      .createQueryBuilder('product')
      .where('product.isActive = :isActive', { isActive: true })
      .andWhere(
        'EXISTS (SELECT 1 FROM brands b WHERE b.id = product.brand_id)',
      )
      .getCount(),
  );

  const block = (sql: string[]): string =>
    '```sql\n' + sql.join(';\n\n') + '\n```';

  const verdict = (ok: boolean, yes: string, no: string): string =>
    ok ? `**${yes}**` : `**${no}**`;

  const report = `# SQL proof — TypeORM ${ormVersion} / ${dbVersion}

Generated by \`npm run sql-proof\` on ${new Date().toISOString().slice(0, 10)}.
Every block below is the SQL actually sent to the database, captured by the TypeORM logger.

---

## 1. \`skip\`/\`take\` + a join + \`getRawMany()\` — pagination disappears

${block(skipTakeSql)}

Result: ${verdict(!hasLimit(skipTakeSql), 'no LIMIT — the query returns EVERY matching row', 'LIMIT present (check your TypeORM version)')}

\`SelectQueryBuilder.createLimitOffsetExpression()\` maps \`skip\`/\`take\` onto
\`OFFSET\`/\`LIMIT\` only when \`joinAttributes.length === 0\`. With a join present, pagination
is handled by the entity path — the one \`getRawMany()\` never takes.

## 2. \`offset\`/\`limit\` + a join + \`getRawMany()\` — pagination works

${block(offsetLimitSql)}

Result: ${verdict(hasLimit(offsetLimitSql), 'LIMIT present', 'no LIMIT')}

## 3. \`getManyAndCount()\` with 1:N joins

${block(getManyAndCountSql)}

Two statements, two different costs. The \`FROM (...) distinctAlias\` subquery picks one
page of distinct ids out of the joined set - MariaDB optimizes it well and it is not where
the time goes. The \`COUNT(DISTINCT ...)\` over the same joined set is the expensive one:
\`results/explain-broad-page-1.json\` has the measured plan for all three - the count
dwarfs the other two by an order of magnitude.

## 4. \`getCount()\` — with and without a join

With a join:

${block(countWithJoinSql)}

Without a join (the condition moved into \`EXISTS\`):

${block(countWithoutJoinSql)}

\`computeCountExpression()\` returns \`COUNT(1)\` only when the query has zero joins.
Any \`innerJoin\` in the counting query — even on a relation that multiplies nothing —
switches COUNT to the \`DISTINCT\` variant.
`;

  const file = join(__dirname, '..', 'results', 'sql-proof.md');
  writeFileSync(file, report);
  console.log(report);
  console.log(`\nzapisane: ${file}`);
});
